import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins , Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
import { SideBar } from "./components/SideBar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ClerkProvider } from "@clerk/nextjs";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${inter.className} antialiased`}
      >
        <ClerkProvider>
         <div className="">
            <SidebarProvider className="flex ">
                <SideBar/>
                <div className="my-8 px-3 flex-1 w-full ">
            {children}
                </div>
            </SidebarProvider>
        </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
